Support use K8s etcd(configmap) as datastore
oam-dev/velacp pull request #139
Opened 2021-07-18 07:17 UTC by wangyuan249

fix #130 

- [x]  Change to store cluster rpc struct info to config map.
- [ ]  Change to store application rpc struct info to config map.
- [ ]  Change to store other object which we didn't define in kubernetes CRD in config map.

2021-07-18 08:06 UTC, wangyuan249 commented
First version，
1. Shall we create a specific namespace when the echo httpserver is starting for better management of vela ui resource, eg: "velaui-system" ?
2. The name for each configmap should be same with the resource name or add a suffix like "appinstance1-schema"
3. After all planned fucntion has been finished,  I would do some code simplification and abstract the shared part.

2021-07-19 03:06 UTC, hongchaodeng commented on go.mod
> +	github.com/prometheus/common v0.10.0
What's this dependency for?

2021-07-19 03:06 UTC, hongchaodeng commented on pkg/rest/services/cluster.go
> +	store     storeadapter.ClusterStore
This store is not used anymore. Right? Why not delete it?

2021-07-23 08:02 UTC, wangyuan249 commented
1. Cause there are many changes involved,  At present, we still lack tests for each condition and situation in different request and response. I only tested the most common scenarios.
2. I will add a description file to introduce how config map store the information and for different types config map we would add a common label for better list and management.
3. For better error report and error location, I would continue to improve the error-throw out mechanism, include http status code, error code definition and error message.

2021-07-26 03:17 UTC, hongchaodeng approved these changes
LGTM

2021-07-28 10:52 UTC, wonderflow requested changes

2021-07-28 10:52 UTC, wonderflow commented on pkg/rest/rest_server.go
> +	}
遇到error确定还要继续？

2021-07-29 13:06 UTC, wangyuan249 commented on pkg/rest/rest_server.go
> +	}
fixed

2021-07-30 07:41 UTC, hongchaodeng commented
@wangyuan249 Please also fix the CI :)

2021-07-30 09:47 UTC, wangyuan249 commented
fix CI
![image](https://user-images.githubusercontent.com/35907099/127635163-d9fbd9db-0337-4e5e-8664-da625734f7c6.png)
![image](https://user-images.githubusercontent.com/35907099/127635237-b176b0de-7284-48bc-83ac-dfb599120de1.png)

2021-07-30 09:49 UTC, wangyuan249 commented
![image](https://user-images.githubusercontent.com/35907099/127635523-2aaa19d7-e470-4f16-9b1d-b8fc9b109768.png)

2021-07-30 12:58 UTC, hongchaodeng commented
Awesome. Thanks!

2021-07-30 12:58 UTC, merged